rvm: 1.8.7
notifications:
  email:
    - <arne@hingst.it>
env:
  - PUPPET_VERSION=2.6.14
  - PUPPET_VERSION=2.7.11
before_install:
  - "echo 'gem: --no-ri --no-rdoc' > ~/.gemrc"
  - gem install bundler
  - "bundle install"
